name: build-labs
on: [ push ]

jobs:
  build:
    name: building-labs
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ windows-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: lukka/get-cmake@latest
      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          runVcpkgInstall: true
          vcpkgGitCommitId: 9ec9fd4d041e87a051dbd058f79740b273095b03
          vcpkgGitURL: https://github.com/LollyBomb-hub/vcpkg_labs_dependencies.git
      - name: Run CMake+vcpkg+Ninja
        uses: lukka/run-cmake@v10
        id: runcmake
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'ninja-multi-vcpkg'
          useVcpkgToolchainFile: true